# Allow using debug dumps. It's not recommended on production servers.
debug: false
# Generators
# You can duplicate default 'nether' generator and create as many generators as you want
generators:
  # Generator name
  nether:
    # Allowed worlds - supports Multiverse-Core (primarily) and other multi world plugins
    worlds:
      - skyworld_nether
    # Generated blocks
    blocks:
      # Use: BLOCK_NAME:CHANCE
      #   For BLOCK_NAME use bukkit names. See https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html.
      #   CHANCE is decimal number from 0-100
      #   Sum of the chances mustn't be more than 100
      - NETHERRACK:90.0
      - SOUL_SAND:10.0
# Messages for translation
# Change only text in quotation marks ("")
# If you need to use quotation mark in your text, use \" instead of "
messages:
  permissions: "You do not have permission to do that!"
  config-reload: "Custom Cobble Gen configuration reloaded!"